/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work;

import static work.GiveMeARandomQuote.kindlyGiveMeARandomQuote;
import static work.GiveMeARandomQuote.kindlyGiveMeARandomQuoteFromApi;

public class App {

    public static void main(String[] args) {
//        System.out.println(kindlyGiveMeARandomQuote());
        System.out.println(kindlyGiveMeARandomQuoteFromApi());

    }
}
